import Foundation

struct StudyLesson: Identifiable {
    let number: Int
    let title: String
    let cards: [StudyLessonCard]

    var id: Int { number }
}

struct StudyLessonCard: Identifiable {
    let character: String
    let pinyin: String
    let meaning: String

    var id: String { "\(character)-\(pinyin)-\(meaning)" }
}

enum StudyLessonData {
    static let lessons: [StudyLesson] = [
        StudyLesson(number: 1, title: "Lesson 1", cards: [
            StudyLessonCard(character: "你", pinyin: "nǐ", meaning: "you"),
            StudyLessonCard(character: "好", pinyin: "hǎo", meaning: "good; well; fine; OK"),
            StudyLessonCard(character: "吗", pinyin: "ma", meaning: "Question Particle (yes-no-question)"),
            StudyLessonCard(character: "我", pinyin: "wǒ", meaning: "I; me"),
            StudyLessonCard(character: "很", pinyin: "hěn", meaning: "very"),
            StudyLessonCard(character: "呢", pinyin: "ne", meaning: "Modal Particle (elliptical question)"),
            StudyLessonCard(character: "也", pinyin: "yě", meaning: "too; also"),
        ]),
        StudyLesson(number: 2, title: "Lesson 2", cards: [
            StudyLessonCard(character: "忙", pinyin: "máng", meaning: "busy"),
            StudyLessonCard(character: "爸爸", pinyin: "bà ba", meaning: "dad"),
            StudyLessonCard(character: "妈妈", pinyin: "mā ma", meaning: "mom"),
            StudyLessonCard(character: "他们", pinyin: "tā men", meaning: "they; them (male)"),
            StudyLessonCard(character: "他", pinyin: "tā", meaning: "he; him"),
            StudyLessonCard(character: "们", pinyin: "men", meaning: "(denote plurality)"),
            StudyLessonCard(character: "都", pinyin: "dōu", meaning: "both; all"),
            StudyLessonCard(character: "不", pinyin: "bù", meaning: "not; no"),
            StudyLessonCard(character: "男", pinyin: "nán", meaning: "male"),
            StudyLessonCard(character: "朋友", pinyin: "péng you", meaning: "friend"),
            StudyLessonCard(character: "哥哥", pinyin: "gē ge", meaning: "elder brother"),
            StudyLessonCard(character: "要", pinyin: "yào", meaning: "to want"),
            StudyLessonCard(character: "咖啡", pinyin: "kā fēi", meaning: "coffee"),
            StudyLessonCard(character: "弟弟", pinyin: "dì di", meaning: "younger brother"),
            StudyLessonCard(character: "我们", pinyin: "wǒ men", meaning: "we; us"),
            StudyLessonCard(character: "喝", pinyin: "hē", meaning: "to drink"),
        ]),
        StudyLesson(number: 3, title: "Lesson 3", cards: [
            StudyLessonCard(character: "她", pinyin: "tā", meaning: "she; her"),
            StudyLessonCard(character: "是", pinyin: "shì", meaning: "to be; is"),
            StudyLessonCard(character: "哪", pinyin: "nǎ", meaning: "which"),
            StudyLessonCard(character: "国", pinyin: "gúo", meaning: "(in combination with other characters) country; nation"),
            StudyLessonCard(character: "人", pinyin: "rén", meaning: "people; person"),
            StudyLessonCard(character: "那", pinyin: "nà", meaning: "that"),
            StudyLessonCard(character: "谁", pinyin: "shéi", meaning: "who; whom"),
            StudyLessonCard(character: "老师", pinyin: "lǎo shī", meaning: "teacher"),
            StudyLessonCard(character: "中国", pinyin: "zhōng gúo", meaning: "China"),
            StudyLessonCard(character: "您", pinyin: "nín", meaning: "you (polite form)"),
            StudyLessonCard(character: "这", pinyin: "zhè", meaning: "this"),
            StudyLessonCard(character: "外语", pinyin: "wài yǔ", meaning: "foreign language"),
            StudyLessonCard(character: "医生", pinyin: "yī shēng", meaning: "doctor; physician"),
            StudyLessonCard(character: "奶奶", pinyin: "nǎi nai", meaning: "(paternal) grandmother"),
            StudyLessonCard(character: "外婆", pinyin: "wài pó", meaning: "(maternal) grandmother"),
        ]),
        StudyLesson(number: 4, title: "Lesson 4", cards: [
            StudyLessonCard(character: "认识", pinyin: "rèn shi", meaning: "to know (somebody)"),
            StudyLessonCard(character: "高兴", pinyin: "gāo xìng", meaning: "happy; pleased (feeling)"),
            StudyLessonCard(character: "高", pinyin: "gāo", meaning: "high; tall"),
            StudyLessonCard(character: "可以", pinyin: "kě yǐ", meaning: "may"),
            StudyLessonCard(character: "进来", pinyin: "jìn lai", meaning: "to come in"),
            StudyLessonCard(character: "进", pinyin: "jìn", meaning: "to enter"),
            StudyLessonCard(character: "来", pinyin: "lái", meaning: "to come"),
            StudyLessonCard(character: "请", pinyin: "qǐng", meaning: "please"),
            StudyLessonCard(character: "记者", pinyin: "jì zhě", meaning: "reporter"),
            StudyLessonCard(character: "请问", pinyin: "qǐng wèn", meaning: "May I ask...?"),
            StudyLessonCard(character: "问", pinyin: "wèn", meaning: "to ask"),
            StudyLessonCard(character: "贵姓", pinyin: "gùi xìng", meaning: "your surname (polite form)"),
            StudyLessonCard(character: "姓", pinyin: "xìng", meaning: "one's surname is... /surname"),
            StudyLessonCard(character: "叫", pinyin: "jiào", meaning: "to be called"),
            StudyLessonCard(character: "先生", pinyin: "xiān sheng", meaning: "mr.; sir"),
            StudyLessonCard(character: "语言", pinyin: "yǔ yán", meaning: "language"),
            StudyLessonCard(character: "学院", pinyin: "xué yuàn", meaning: "institute; college"),
            StudyLessonCard(character: "学", pinyin: "xué", meaning: "to learn; to study (short)"),
            StudyLessonCard(character: "的", pinyin: "de", meaning: "of (a possessive or noun modifying particle)"),
            StudyLessonCard(character: "学生", pinyin: "xué shēng", meaning: "student"),
            StudyLessonCard(character: "什么", pinyin: "shén me", meaning: "what"),
            StudyLessonCard(character: "学习", pinyin: "xué xí", meaning: "to learn; to study (long)"),
            StudyLessonCard(character: "汉语", pinyin: "hàn yǔ", meaning: "Chinese (spoken language)"),
            StudyLessonCard(character: "英国", pinyin: "yīng gúo", meaning: "Great Britain; England"),
            StudyLessonCard(character: "加拿大", pinyin: "jiā ná dà", meaning: "Canada"),
            StudyLessonCard(character: "美国", pinyin: "měi gúo", meaning: "the United States of America"),
        ]),
        StudyLesson(number: 5, title: "Lesson 5", cards: [
            StudyLessonCard(character: "餐厅", pinyin: "cān tīng", meaning: "dining hall"),
            StudyLessonCard(character: "在", pinyin: "zài", meaning: "to be (here, there); to be (in, on, at)"),
            StudyLessonCard(character: "哪儿", pinyin: "nǎr", meaning: "where"),
            StudyLessonCard(character: "宿舍", pinyin: "sù shè", meaning: "dormitory"),
            StudyLessonCard(character: "女", pinyin: "nǚ", meaning: "female"),
            StudyLessonCard(character: "坐", pinyin: "zùo", meaning: "to sit"),
            StudyLessonCard(character: "谢谢", pinyin: "xiè xie", meaning: "to thank"),
            StudyLessonCard(character: "对不起", pinyin: "dùi bu qǐ", meaning: "I'm sorry"),
            StudyLessonCard(character: "知道", pinyin: "zhī dào", meaning: "to know"),
            StudyLessonCard(character: "没关系", pinyin: "méi guān xi", meaning: "never mind; it doesn't matter"),
            StudyLessonCard(character: "再见", pinyin: "zài jiàn", meaning: "goodbye"),
            StudyLessonCard(character: "再", pinyin: "zài", meaning: "again (future)"),
            StudyLessonCard(character: "小姐", pinyin: "xiǎo jiě", meaning: "Miss; young lady"),
            StudyLessonCard(character: "二", pinyin: "èr", meaning: "two"),
            StudyLessonCard(character: "层", pinyin: "céng", meaning: "story; floor (how many floors)"),
            StudyLessonCard(character: "零", pinyin: "líng", meaning: "zero"),
            StudyLessonCard(character: "四", pinyin: "sì", meaning: "four"),
            StudyLessonCard(character: "号", pinyin: "hào", meaning: "ordinal number"),
            StudyLessonCard(character: "不用", pinyin: "bú yòng", meaning: "need not"),
            StudyLessonCard(character: "这儿", pinyin: "zhèr", meaning: "here"),
            StudyLessonCard(character: "晚", pinyin: "wǎn", meaning: "late"),
            StudyLessonCard(character: "了", pinyin: "le", meaning: "(simple past; a modal particle; aspect particle)"),
        ]),
        StudyLesson(number: 6, title: "Lesson 6", cards: [
            StudyLessonCard(character: "去", pinyin: "qù", meaning: "to go"),
            StudyLessonCard(character: "游泳", pinyin: "yóu yǒng", meaning: "to swim"),
            StudyLessonCard(character: "昨天", pinyin: "zúo tiān", meaning: "yesterday"),
            StudyLessonCard(character: "京剧", pinyin: "jīng jù", meaning: "Peking/Beijing opera"),
            StudyLessonCard(character: "怎么样", pinyin: "zěn me yàng", meaning: "how is ..."),
            StudyLessonCard(character: "有意思", pinyin: "yǒu yì si", meaning: "interesting"),
            StudyLessonCard(character: "今天", pinyin: "jīn tiān", meaning: "today"),
            StudyLessonCard(character: "天", pinyin: "tiān", meaning: "day"),
            StudyLessonCard(character: "天气", pinyin: "tiān qì", meaning: "weather"),
            StudyLessonCard(character: "太", pinyin: "tài", meaning: "too; extremely"),
            StudyLessonCard(character: "时候", pinyin: "shí hou", meaning: "time; moment"),
            StudyLessonCard(character: "现在", pinyin: "xiàn zài", meaning: "now"),
            StudyLessonCard(character: "明天", pinyin: "míng tiān", meaning: "tomorrow"),
            StudyLessonCard(character: "有", pinyin: "yǒu", meaning: "to have"),
            StudyLessonCard(character: "时间", pinyin: "shí jiān", meaning: "time"),
            StudyLessonCard(character: "说", pinyin: "shūo", meaning: "to say; to speak"),
            StudyLessonCard(character: "遍", pinyin: "biàn", meaning: "(a measure word having done something x times)"),
            StudyLessonCard(character: "打球", pinyin: "dǎ qiú", meaning: "to play ball games (with hand)"),
            StudyLessonCard(character: "打", pinyin: "dǎ", meaning: "to hit"),
            StudyLessonCard(character: "球", pinyin: "qiú", meaning: "ball"),
            StudyLessonCard(character: "抱歉", pinyin: "bào qiàn", meaning: "sorry"),
            StudyLessonCard(character: "恐怕", pinyin: "kǒng pà", meaning: "afraid that ..."),
            StudyLessonCard(character: "行", pinyin: "xíng", meaning: "to be OK; it's alright; it works"),
            StudyLessonCard(character: "你们", pinyin: "nǐ men", meaning: "you (pl.)"),
        ]),
        StudyLesson(number: 7, title: "Lesson 7", cards: [
            StudyLessonCard(character: "开学", pinyin: "kāi xué", meaning: "school opens; term begins"),
            StudyLessonCard(character: "开", pinyin: "kāi", meaning: "to open; to start; to drive/operate (a vehicle); to run/operate (a business)"),
            StudyLessonCard(character: "看", pinyin: "kàn", meaning: "to watch; to look at"),
            StudyLessonCard(character: "一下", pinyin: "yí xià", meaning: "(used after a verb to indicate a short, quick, random, informal action)"),
            StudyLessonCard(character: "名片", pinyin: "míng piàn", meaning: "business card"),
            StudyLessonCard(character: "啊", pinyin: "à", meaning: "ah; oh"),
            StudyLessonCard(character: "教授", pinyin: "jiào shòu", meaning: "professor"),
            StudyLessonCard(character: "教", pinyin: "jiāo", meaning: "to teach; to instruct"),
            StudyLessonCard(character: "介绍", pinyin: "jiè shào", meaning: "to introduce"),
            StudyLessonCard(character: "名字", pinyin: "míng zi", meaning: "name (first name)"),
            StudyLessonCard(character: "中文", pinyin: "zhōng wén", meaning: "Chinese"),
            StudyLessonCard(character: "专业", pinyin: "zhuān yè", meaning: "major; speciality"),
            StudyLessonCard(character: "美术", pinyin: "měi shù", meaning: "fine arts"),
            StudyLessonCard(character: "美", pinyin: "měi", meaning: "beautiful"),
            StudyLessonCard(character: "文学", pinyin: "wén xué", meaning: "literature"),
        ]),
        StudyLesson(number: 8, title: "Lesson 8", cards: [
            StudyLessonCard(character: "家", pinyin: "jiā", meaning: "family; home"),
            StudyLessonCard(character: "几", pinyin: "jǐ", meaning: "a few; several; how many; how much"),
            StudyLessonCard(character: "口", pinyin: "kǒu", meaning: "(a measure word mainly for the number of people in a family)"),
            StudyLessonCard(character: "照片", pinyin: "zhào piàn", meaning: "picture; photo (in photography)"),
            StudyLessonCard(character: "和", pinyin: "hé", meaning: "and"),
            StudyLessonCard(character: "个", pinyin: "gè", meaning: "(a measure word for general use)"),
            StudyLessonCard(character: "姐姐", pinyin: "jiě jie", meaning: "elder sister"),
            StudyLessonCard(character: "两", pinyin: "liǎng", meaning: "two (not for counting)"),
            StudyLessonCard(character: "一共", pinyin: "yí gòng", meaning: "altogether"),
            StudyLessonCard(character: "还", pinyin: "hái", meaning: "in addition; still"),
            StudyLessonCard(character: "妹妹", pinyin: "mèi mei", meaning: "younger sister"),
            StudyLessonCard(character: "小", pinyin: "xiǎo", meaning: "little; small"),
            StudyLessonCard(character: "狗", pinyin: "gǒu", meaning: "dog"),
            StudyLessonCard(character: "当然", pinyin: "dāng rán", meaning: "of course"),
            StudyLessonCard(character: "张", pinyin: "zhāng", meaning: "(a measure word for flat objects)"),
            StudyLessonCard(character: "真", pinyin: "zhēn", meaning: "real; really"),
            StudyLessonCard(character: "可爱", pinyin: "ke'3 ài", meaning: "lovely; cute"),
            StudyLessonCard(character: "爱", pinyin: "ài", meaning: "to love (verb)"),
            StudyLessonCard(character: "没", pinyin: "méi", meaning: "not; none"),
            StudyLessonCard(character: "做", pinyin: "zùo", meaning: "to do; to be; to make"),
            StudyLessonCard(character: "工作", pinyin: "gōng zùo", meaning: "to work; work; job"),
            StudyLessonCard(character: "大", pinyin: "dà", meaning: "big; large"),
            StudyLessonCard(character: "多少", pinyin: "dūo shǎo", meaning: "how many; how much"),
            StudyLessonCard(character: "多", pinyin: "dūo", meaning: "many; much"),
            StudyLessonCard(character: "少", pinyin: "shǎo", meaning: "few; less; little"),
            StudyLessonCard(character: "喜欢", pinyin: "xǐ huan", meaning: "to like"),
            StudyLessonCard(character: "外", pinyin: "wài", meaning: "foreign; outside"),
            StudyLessonCard(character: "语", pinyin: "yǔ", meaning: "(a countries) language"),
            StudyLessonCard(character: "外国", pinyin: "wài gúo", meaning: "foreign country"),
            StudyLessonCard(character: "百", pinyin: "bǎi", meaning: "hundred"),
        ]),
        StudyLesson(number: 9, title: "Lesson 9", cards: [
            StudyLessonCard(character: "今年", pinyin: "jīn nián", meaning: "this year"),
            StudyLessonCard(character: "岁", pinyin: "sùi", meaning: "year ('s old)"),
            StudyLessonCard(character: "课", pinyin: "kè", meaning: "class; Lesson"),
            StudyLessonCard(character: "星期", pinyin: "xīng qī", meaning: "week"),
            StudyLessonCard(character: "上午", pinyin: "shàng wǔ", meaning: "morning"),
            StudyLessonCard(character: "上", pinyin: "shàng", meaning: "above; up; upper; go up; last; previous"),
            StudyLessonCard(character: "下午", pinyin: "xià wǔ", meaning: "afternoon"),
            StudyLessonCard(character: "下", pinyin: "xià", meaning: "below; down; to go down; to get off; next"),
            StudyLessonCard(character: "星期日", pinyin: "xīng qī rì", meaning: "Sunday"),
            StudyLessonCard(character: "生日", pinyin: "shēng rì", meaning: "birthday"),
            StudyLessonCard(character: "生", pinyin: "shēng", meaning: "to be born"),
            StudyLessonCard(character: "多大", pinyin: "dūo dà", meaning: "how old"),
            StudyLessonCard(character: "出生", pinyin: "chū shēng", meaning: "to be born (in the year XXXX)"),
            StudyLessonCard(character: "出", pinyin: "chū", meaning: "to go (outside); to come out"),
            StudyLessonCard(character: "属", pinyin: "shǔ", meaning: "to be born in the year of (one of the 12 animals)"),
            StudyLessonCard(character: "聚会", pinyin: "jù hùi", meaning: "get-together; party"),
            StudyLessonCard(character: "会", pinyin: "hùi", meaning: "meeting; to have the knowledge of; can"),
            StudyLessonCard(character: "祝贺", pinyin: "zhù hè", meaning: "to congratulate"),
            StudyLessonCard(character: "祝", pinyin: "zhù", meaning: "to wish"),
            StudyLessonCard(character: "参加", pinyin: "cān jiā", meaning: "to participate; to attend"),
            StudyLessonCard(character: "过", pinyin: "gùo", meaning: "to spend (time); to celebrate (someone's birthday, a festival etc.)"),
            StudyLessonCard(character: "吃", pinyin: "chī", meaning: "to eat"),
            StudyLessonCard(character: "蛋糕", pinyin: "dàn gāo", meaning: "cake"),
            StudyLessonCard(character: "蛋", pinyin: "dàn", meaning: "egg"),
            StudyLessonCard(character: "糕", pinyin: "gāo", meaning: "(with other characters: used for all kinds of sweets, mainly cakes)"),
            StudyLessonCard(character: "买", pinyin: "mǎi", meaning: "to buy"),
            StudyLessonCard(character: "瓶", pinyin: "píng", meaning: "bottle"),
            StudyLessonCard(character: "红葡萄酒", pinyin: "hóng pú tao jiǔ", meaning: "red wine"),
            StudyLessonCard(character: "红", pinyin: "hóng", meaning: "red"),
            StudyLessonCard(character: "葡萄", pinyin: "pú tao", meaning: "grape"),
            StudyLessonCard(character: "酒", pinyin: "jiǔ", meaning: "wine or liquor"),
            StudyLessonCard(character: "北京", pinyin: "běi jīng", meaning: "Beijing"),
            StudyLessonCard(character: "快乐", pinyin: "kuài lè", meaning: "happy (birthday)"),
            StudyLessonCard(character: "漂亮", pinyin: "piào liang", meaning: "beautiful; nice; cute (for girls)"),
            StudyLessonCard(character: "烤鸭", pinyin: "kǎo yā", meaning: "roast duck"),
            StudyLessonCard(character: "鸭", pinyin: "yā", meaning: "duck"),
            StudyLessonCard(character: "长寿面", pinyin: "cháng shòu miàn", meaning: "(birthday) longevity noodles"),
            StudyLessonCard(character: "面", pinyin: "miàn", meaning: "face; side; surface; classifier for flat surfaces"),
        ]),
        StudyLesson(number: 10, title: "Lesson 10", cards: [
            StudyLessonCard(character: "光盘", pinyin: "guāng pán", meaning: "CD"),
            StudyLessonCard(character: "常", pinyin: "cháng", meaning: "often (single char)"),
            StudyLessonCard(character: "跟", pinyin: "gēn", meaning: "with; to follow"),
            StudyLessonCard(character: "商场", pinyin: "shāng chǎng", meaning: "market; bazaar; shopping mall"),
            StudyLessonCard(character: "商", pinyin: "shāng", meaning: "trade; commerce; business"),
            StudyLessonCard(character: "有名", pinyin: "yǒu míng", meaning: "famous"),
            StudyLessonCard(character: "书", pinyin: "shū", meaning: "book"),
            StudyLessonCard(character: "报纸", pinyin: "bào zhǐ", meaning: "newspaper"),
            StudyLessonCard(character: "本子", pinyin: "běn zi", meaning: "exercise book; notebook"),
            StudyLessonCard(character: "那儿", pinyin: "nàr", meaning: "there"),
            StudyLessonCard(character: "师傅", pinyin: "shī fu", meaning: "master"),
            StudyLessonCard(character: "香蕉苹果", pinyin: "xiāng jiāo píng gǔo", meaning: "apple with the taste of a banana"),
            StudyLessonCard(character: "香蕉", pinyin: "xiāng jiāo", meaning: "banana"),
            StudyLessonCard(character: "苹果", pinyin: "píng gǔo", meaning: "apple"),
            StudyLessonCard(character: "怎么", pinyin: "zěn me", meaning: "how"),
            StudyLessonCard(character: "容易", pinyin: "róng yì", meaning: "easy"),
            StudyLessonCard(character: "斤", pinyin: "jīn", meaning: "(a measure word of weight, it is equal to 500g)"),
            StudyLessonCard(character: "钱", pinyin: "qián", meaning: "money"),
            StudyLessonCard(character: "块钱", pinyin: "kuài (qian)2", meaning: "(a measure word of a Chinese monetary unit, eq to 10 jiao) kuai"),
            StudyLessonCard(character: "毛钱", pinyin: "máo (qian)2", meaning: "(a measure word of a Chinese monetary unit, eq to 1/10 yuan) mao"),
            StudyLessonCard(character: "贵", pinyin: "gùi", meaning: "expensive; precious"),
            StudyLessonCard(character: "分钱", pinyin: "fēn (qian)2", meaning: "(a measure word of a Chinese monetary unit, eq to 1/100 yuan) fen"),
            StudyLessonCard(character: "送", pinyin: "sòng", meaning: "to give (as a present)"),
            StudyLessonCard(character: "给", pinyin: "gěi", meaning: "to give (sth)"),
            StudyLessonCard(character: "找钱", pinyin: "zhǎo (qian)2", meaning: "to give change"),
        ]),
        StudyLesson(number: 11, title: "Lesson 11", cards: [
            StudyLessonCard(character: "（一）点儿", pinyin: "(yi)4 diǎnr", meaning: "a little bit"),
            StudyLessonCard(character: "司机", pinyin: "sī jī", meaning: "driver"),
            StudyLessonCard(character: "点（钟）", pinyin: "diǎn (zhong)1", meaning: "o'clock"),
            StudyLessonCard(character: "差", pinyin: "chà", meaning: "to be short of; to lack"),
            StudyLessonCard(character: "刻", pinyin: "kè", meaning: "quarter (of an hour)"),
            StudyLessonCard(character: "回", pinyin: "húi", meaning: "to return"),
            StudyLessonCard(character: "上课", pinyin: "shàng kè", meaning: "to go to class (for both students and teachers)"),
            StudyLessonCard(character: "能", pinyin: "néng", meaning: "to be able to (can)"),
            StudyLessonCard(character: "到", pinyin: "dào", meaning: "to arrive"),
            StudyLessonCard(character: "哪里", pinyin: "nǎ li", meaning: "no (an expression of mild denial， after a compliment)"),
            StudyLessonCard(character: "孙女儿", pinyin: "sūn nvr", meaning: "granddaughter on son's side"),
            StudyLessonCard(character: "岁数", pinyin: "sùi shu", meaning: "age (of sb./sth.)"),
            StudyLessonCard(character: "数", pinyin: "shù", meaning: "number"),
            StudyLessonCard(character: "分（钟）", pinyin: "fēn (zhong)1", meaning: "minute"),
            StudyLessonCard(character: "拜拜", pinyin: "bái bái", meaning: "bye-bye (transliteration)"),
            StudyLessonCard(character: "为什么", pinyin: "wèi shén me", meaning: "why"),
            StudyLessonCard(character: "为", pinyin: "wèi", meaning: "for"),
            StudyLessonCard(character: "玩儿", pinyin: "wánr", meaning: "to have fun; to play"),
            StudyLessonCard(character: "半", pinyin: "bàn", meaning: "half"),
            StudyLessonCard(character: "写", pinyin: "xiě", meaning: "to write"),
            StudyLessonCard(character: "汉字", pinyin: "hàn zì", meaning: "Chinese character"),
            StudyLessonCard(character: "字", pinyin: "zì", meaning: "character"),
            StudyLessonCard(character: "睡觉", pinyin: "shùi jiào", meaning: "to go to bed; to sleep"),
            StudyLessonCard(character: "睡", pinyin: "shùi", meaning: "to sleep; to lie down"),
            StudyLessonCard(character: "起床", pinyin: "qǐ chuáng", meaning: "to get up (from bed)"),
            StudyLessonCard(character: "起", pinyin: "qǐ", meaning: "to get up; to rise"),
            StudyLessonCard(character: "床", pinyin: "chuáng", meaning: "bed"),
            StudyLessonCard(character: "应该", pinyin: "yīng gāi", meaning: "must; should; ought to"),
            StudyLessonCard(character: "该", pinyin: "gāi", meaning: "probably; should; ought to"),
            StudyLessonCard(character: "问题", pinyin: "wèn tí", meaning: "question, problem"),
        ]),
    ]
}
